### ISSUE TITLE
Option to select server ip to bind to

### ISSUE THREAD

**Issue by csakshaug** [inlets/inlets#113]
On server feature, it should be an option to bind to specified IP instead of * (:) like now.

## Current Behaviour
It binds to 0.0.0.0:80 or :::8080

## Possible Solution
Add ip to bind to so we can bind to 127.0.0.1:8080 and only expose the server through caddy/nginx etc..

**Comment by alexellis** [comment]
That sounds like a good idea. You can also change the control-port if that's helpful for the time being.
