### ISSUE TITLE
Scaleway image not available

### ISSUE THREAD

**Issue by meyerf99** [inlets/inlets#118]
## Expected Behaviour

VPS on Scaleway provider should be created successfully.

## Current Behaviour

Currently there is an FATAL error because Ubuntu image **ubuntu-mini-xenial-25g** is not available.
`FATA[0001] cannot execute 'run': failed to create server: No such image (zone ams1, arch x86_64) : ubuntu-mini-xenial-25g `

## Possible Solution

Changing image from **ubuntu-mini-xenial-25g** to **Ubuntu_Bionic** in ./hack/provision-scaleway.sh on line 11.
## Steps to Reproduce (for bugs)

1. Open Terminal on Mac OSX/Linux
2. Go into inlets directory
3. Run ./hack/provision-scaleway.sh script

## Context

Currently it's not possible to deploy inlets Exit-Node on Scaleway with auto-provision script.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
**Mac OSX 10.15**

**Comment by alexellis** [comment]
Hi thanks for raising the issue

I'm not currently a scaleway customer so if you want to fix this please feel free to propose that.

The DigitalOcean option is working if you want to use that. 

Cc @rgee0

**Comment by meyerf99** [comment]
Hi @alexellis 

I'll do a PR with the change.

**Comment by alexellis** [comment]
Should we go for the cheapest Dev option?

**Comment by alexellis** [comment]
Thank you
