### ISSUE TITLE
[Feature] Support Hetzner auto provision

### ISSUE THREAD

**Issue by meyerf99** [inlets/inlets#120]
## Feature Request

It would be great to have an auto provision support for [Hetzner](https://www.hetzner.com/).
In addition to Scaleway & Digital Ocean, Hetzner also offers very cheap hosting for inlets.
Currently they support two DataCenter countries (Germany & Finland).

I would try in the next few days to get an auto provision support for Hetzner if this fits for you?

**Comment by alexellis** [comment]
What sort of costs are we looking at?

If you submitted the patch would you be willing to maintain it?

**Comment by alexellis** [comment]
Just a thought - there is no "auto-provision" in the inlets code, perhaps you're thinking of the inlets-operator? https://github.com/inlets/inlets-operator/

Are you thinking of a bash script like the one for DO, or the K8s operator?

**Comment by alexellis** [comment]
@meyerf99 closing as I've not heard from you in a couple of months. Feel free to raise an issue for the operator if that's what you meant, or inletsctl which hosts the provision package for different IaaS.
