### ISSUE TITLE
Translation of the docs to Chinese

### ISSUE THREAD

**Issue by wi1dcard** [inlets/inlets#124]
Hi team,

I've use inlets for months, and it's such a great project that using the WebSocket protocol, which can be deployed behind Kubernetes ingresses.

Today, I found there's a "gfw" tag under this repo. That makes me think this project is much much useful in China which we (I mean, I'm in China too) 1) could not get a public IP address for personal broadband service; 2) even for an enterprise broadband connection, the ISP requires lots of paperwork and procedures for an opening 80/443 port. Recently, Shanghai is now asking all primary ISPs to inspect all undocumented HTTP services on all ports of personal broadbands.

So, I would suggest if we could make these docs translated into Chinese, that would be great for the Chinese users who do not have proficient English skills. 

What do you guys think? I'm happy to do this work.

**Comment by alexellis** [comment]
Hi @wi1dcard it'd be great to get more users from China and this project could help with users facing issues with gfw.

Please feel free to submit a PR of README_CN.md

Alex
