### ISSUE TITLE
Listen to more than one port with --port parameter

### ISSUE THREAD

**Issue by marcosvrs** [inlets/inlets#128]
I would like to forward multiple ports to my client (80 and 443). So I can manage the reverse proxy on my client side.

## Expected Behaviour
The port parameter could accept more than one port:
`inlets server —port 80,443 —control-port 8080`

## Current Behaviour
Currently, the port parameter only accepts one port:
`inlets server —port 80 —control-port 8080`

## Context
Currently I’m running inlets server in gcloud with caddy. I have to use caddy only for listen to the port 443 and foward to inlets. Because I already have Traefik on my client side working together with all my docker containers.
If inlets server could listen to more than one port, I could avoid the installation of caddy on the server side.

**Comment by alexellis** [comment]
inlets-pro can listen to as many ports as you like and has built-in TLS for the control-port.

Feel free to take a look, it works with inlets-operator and inletsctl - https://github.com/inlets/inlets-pro-pkg

As for your Caddy example I don't follow what the problem is. Can you share the configuration you're using and how it's not working how you need it to?

**Comment by marcosvrs** [comment]
My caddy is working fine. The problem is that I wouldn’t need it if inlets would listen to more than one port. But looks like I need to pay for it 😔

**Comment by dantuluri** [comment]
Check out Alex's blog post. He highlights this to use multiple ports. At the moment it's not working for me, but will update if I do get it to work.

> If you have multiple domain names and multiple services on your laptop simply change the --upstream flag to reflect that.
> 
> For OpenFaaS on Docker Swarm that may be:

> 
> ```
> inlets client \
>  --remote wss://exit.domain.com \
>  --upstream=gateway.domain.com=http://127.0.0.1:8080,prometheus.domain.com=http://127.0.0.1:9090
> ```

**Comment by dantuluri** [comment]
Found another example in the main README
```
inlets client \
 --remote=$REMOTE \
 --token $TOKEN \
 --upstream="store1.example.com=http://127.0.0.1:8001,store2.example.com=http://127.0.0.1:8002"
```

In either case, doesn't work for me. Here's what I'm doing, so hopefully someone can tell me if I'm doing something wrong:

**Server**:
Caddyfile:
```
exit.domain.com

proxy / 127.0.0.1:8080 {
  transparent
}

proxy /tunnel 127.0.0.1:8080 {
  transparent
  websocket
}
```
I then get a successful response saying it's running on port 80 and 443.

**Client**
```
inlets client --remote wss://exit.domain.com --upstream="subdomain.domain.com=http://0.0.0.0:5000,anotherSubdomain.domain.com=http://0.0.0.0:8081" --token=mytoken
```
This doesn't work.

If I were to just do 1 subdomain and replace exit.domain.com with that subdomain in the Caddyfile, everything works great.

Note that all subdomains including exit are pointed to the server IP (on Cloudflare, but I've tried with their proxy on and off (orange and gray cloud to be abstract)).

**Comment by dantuluri** [comment]
Solved.
Not familiar with Caddy (normally just use Traefik or NGINX), but seems like my Caddyfile should've looked like this:

```
exit.domain.com {

proxy / 127.0.0.1:8080 {
  transparent
}

proxy /tunnel 127.0.0.1:8080 {
  transparent
  websocket
}
 
}

subdomain.domain.com {

proxy / 127.0.0.1:8080 {
  transparent
}

proxy /tunnel 127.0.0.1:8080 {
  transparent
  websocket
}

}

anotherSubdomain.domain.com {

proxy / 127.0.0.1:8080 {
  transparent
}

proxy /tunnel 127.0.0.1:8080 {
  transparent
  websocket
}

}
```

And used the same
```
inlets client --remote wss://exit.domain.com --upstream="subdomain.domain.com=http://0.0.0.0:5000,anotherSubdomain.domain.com=http://0.0.0.0:8081" --token=mytoken
```
command for client.

So far looking good. Try this if you want to use multiple ports.

**Comment by alexellis** [comment]
Two separate topics here:

1) Will inlets listen on more than one port?

Inlets Pro listens on whatever ports you like and forwards TCP / L4 1:1 https://github.com/inlets/inlets-pro-pkg

inlets can be used with Caddy to listen on additional ports, but already separates out the control port and data port, you can just rebind Caddy to multiple ports if you want. You really have to be specific about your requirements as one size doesn't fit all, so ask me for something specific and I'll give you a config for that

2) Some users are confused about --upstream

`--upstream` as defined in the docs works as expected, it's used to have a single exit server point to multiple servers

So the example given is the OpenFaaS gateway and Prometheus:

One exit server / host and one inlets, but all served over port 8080 for instance, the Host header determines which server to forward to when the client receives the data.

**Comment by alexellis** [comment]
Locking this thread as it's gotten way off topic, please use our proper channels for technical support - either OpenFaaS Slack and the #inlets channel, or paid support via OpenFaaS Ltd
