### ISSUE TITLE
Feature request: Websocket tunnelling

### ISSUE THREAD

**Issue by matthiasg** [inlets/inlets#13]
Since it is already based on WebSockets, actually also allowing WebSockets should be rather simple to add too right ?

I am specifically thinking of enabling e.g connecting to a node.js inspector port (with some cookie/session/ip based authentication on the frontend for example etc) which would require HTTPS and WebSockets.

**Comment by alexellis** [comment]
Hi @matthiasg I think that would take some additional work and perhaps some re-designing of the code which is currently serialising individual http requests and responses down the websocket tunnel. Have you tried using an ssh tunnel or port-forwarding?

**Comment by matthiasg** [comment]
@alexellis i am looking for a solution to make some virtual machines hidden behind haproxy debuggable on-demand without messing with the haproxy config at runtime for this. having a more dynamic 'routing' layer that i could secure would be nice.

**Comment by alexellis** [comment]
Conceptually this should be possible now, since we made the 2.0 release which uses net/dialer and doesn't couple to a HTTP stack.

@matthiasg what protocol do you want to run over haproxy to the VM?

Alex

**Comment by alexellis** [comment]
@matthiasg I pinged you but don't know if this got lost? It was 6 months ago so I'll close the issue. Hopefully you'll get the second message from me.

**Comment by matthiasg** [comment]
@alexellis must have missed that sorry. As I said I am looking to opening the node debugger protocol on a per use-case basis to debug server side code on demand without having direct access to the machine.

If websockets are supported with inlets this should work now and I will try it with this instead of rolling our own.

**Comment by tanc** [comment]
@alexellis sorry to post on a closed thread but just wanted to check whether Inlets supports proxying websockets in the free version? For example if I have Caddy V2 proxying everything back to inlets should the upstream server be receiving websockets?
