### ISSUE TITLE
888888

### ISSUE THREAD

**Issue by tad888888** [inlets/inlets#131]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets version `inlets --version` 

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by parthkhosla23** [comment]
Its usual

**Comment by tad888888** [comment]
> Its usual
