### ISSUE TITLE
How to make 2 non-local network computer communicates like zerotier does?

### ISSUE THREAD

**Issue by jinfagang** [inlets/inlets#134]
Thanks for this wonderful project!!

After reading about tutorial, seems inlets does, is simply make a request of server (on cloud) can be transfered to local computer. But, what if, we can make 2 computers which **not in the same local network** communicates powered by inlets, how to do that? 

For reference, zerotier is doing same thing, but that is close source and not really reliable in someplaces such as Russia and China.

**Comment by alexellis** [comment]
Hi @jinfagang please can you fill out the whole issue template?

https://raw.githubusercontent.com/inlets/inlets/master/.github/ISSUE_TEMPLATE.md

I need more information than you've provided, thanks.

Alex

**Comment by alexellis** [comment]
Closing as inactive.

inlets PRO may be useful for what you're asking. Feel free to apply for a trial https://docs.inlets.dev/
