### ISSUE TITLE
Host IP change 

### ISSUE THREAD

**Issue by stevesloka** [inlets/inlets#135]
Does inlets update the connection if the IP changes? For instance, if I deploy on one network, then move to another, will the tunnel between the inlets operator and the remote host be updated? 

Right now I'm finding that it's not happening. What would be the process of forcing this update? Just delete the remote VM?

**Comment by alexellis** [comment]
Hi @stevesloka please can you use the whole issue template? https://raw.githubusercontent.com/inlets/inlets/master/.github/ISSUE_TEMPLATE.md

Your report is lacking a lot of information and the template is designed to help us, help you.

This is also not the repo for the [inlets-operator](https://github.com/inlets/inlets-operator), did you mean to raise an issue here?

Looking forward to hearing more from you.

Alex

**Comment by alexellis** [comment]
Let me know @stevesloka, issues can also be transferred if you got the repo wrong. I see you closed the issue but still haven't given any instructions for repro?

**Comment by stevesloka** [comment]
@alexellis This was probably the wrong repo and should be in the operator one, no worries my use-case is no longer needed. Thanks!
