### ISSUE TITLE
TLS oversized record error

### ISSUE THREAD

**Issue by shrasool** [inlets/inlets#136]
While trying to tunnel HTTPS traffic, I am getting a TLS error pasted below.

## Expected Behaviour

HTTPS traffic should also work with this setup.

## Current Behaviour

I have set up an inlets server using the daemon service from this [systemd service gist](https://raw.githubusercontent.com/alexellis/inlets/master/hack/inlets.service) by adjusting my port to 8080. Using a normal http nginx server, everything is fine:
```
inlets client  --remote=$REMOTE  --upstream=http://127.0.0.1:35100  --token="$TOKEN"
2019/12/10 14:53:49 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2019/12/10 14:53:49 Starting client - version 2.6.3
2019/12/10 14:53:49 Upstream:  => http://127.0.0.1:35100
2019/12/10 14:53:49 Token:
INFO[0000] Connecting to proxy                           url="ws://10.X.Y.Z:8080/tunnel"
```
I am able to retrieve the webpage using http://10.X.Y.Z:8080
But when I change it to expose another service running HTTPS, I am hit by this error:
```
inlets client  --remote=$REMOTE  --upstream=https://127.0.0.1:8154 --token="$TOKEN"
2019/12/10 14:55:30 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2019/12/10 14:55:30 Starting client - version 2.6.3
2019/12/10 14:55:30 Upstream:  => https://127.0.0.1:8154
2019/12/10 14:55:30 Token:
INFO[0000] Connecting to proxy                           url="wss://10.X.Y.Z:8080/tunnel"
ERRO[0000] Failed to connect to proxy                    error="tls: oversized record received with length 20527"
ERRO[0000] Failed to connect to proxy                    error="tls: oversized record received with length 20527"
INFO[0005] Connecting to proxy                           url="wss://10.X.Y.Z:8080/tunnel"
ERRO[0005] Failed to connect to proxy                    error="tls: oversized record received with length 20527"
ERRO[0005] Failed to connect to proxy                    error="tls: oversized record received with length 20527"
```

## Steps to Reproduce (for bugs)

1. Set up inlets server.
2. Verify connection by initiating simple HTTP server on localhost and setting inlets client using normal ws://URL-of-server:port
3. Stop the connection in step 2. Set up some HTTPS service, e.g. portainer UI and setting inlets client using wss://URL-of-server:port
4. Get the error

## Context

I first tried without using ws: or wss: in the $REMOTE and the tunnel connected but I could not get any traffic through for https. After re-reading the README Status, I changed it to use wss://Server-IP .
Btw, the client and server VMs are on different subnets in AWS.

## Your Environment

* inlets version `inlets --version` 
Version: 2.6.3
Git Commit: c2033ecaaef9381d975a3fcadb86011056865fb9
btw, **inlets --version** throws 
`inlets --version`
`Error: unknown flag: --version`.
Command is `inlets version`
* Docker/Kubernetes version `docker version` / `kubectl version`:
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
Amazon Linux 2
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Please can you give the actual steps 1-1? Thanks. 

Also are you saying this is an issue only when forwarding Portainer?

**Comment by alexellis** [comment]
Let me know?

**Comment by shrasool** [comment]
Let me re-try the setup today!

**Comment by alexellis** [comment]
Cheers, let us know?

**Comment by shrasool** [comment]
Let me reproduce it more generically!

**Comment by rt1410201** [comment]
Hi
