### ISSUE TITLE
detect inlets server that has no connection in several minutes to shutdown

### ISSUE THREAD

**Issue by goldalworming** [inlets/inlets#138]
hi, is it possible to detect inlets service that has no connection in several minutes. I make automatic run inlets server on empty port but no idea to close it when there is no connection for several minutes

**Comment by alexellis** [comment]
Hi, I don't understand what you're asking for, please can you use the proper issue template? I'll give you a few days to fill this out otherwise will be closing the issue.

Alex

**Comment by alexellis** [comment]
https://raw.githubusercontent.com/inlets/inlets/master/.github/ISSUE_TEMPLATE.md
