### ISSUE TITLE
Consider adding inlets to scoop for windows users

### ISSUE THREAD

**Issue by gldraphael** [inlets/inlets#140]
## Expected Behaviour

(Scoop is like brew for windows; scoop buckets are like brew taps).    
Windows users should be able to install inlets using scoop:

```sh
scoop install inlets
```

## Current Behaviour

Users need to manually download the exe from github releases and update `$PATH`.

## Possible Solution

Add a file like: https://github.com/gldraphael/scoop-bucket/blob/master/bucket/inlets.json
to [`scoop/main`](https://github.com/ScoopInstaller/Main/tree/master/bucket) or  [`scoop/extras`](https://github.com/lukesampson/scoop-extras), or to inlet's own bucket similar to [mine](https://github.com/gldraphael/scoop-bucket/tree/master/bucket).

**Comment by alexellis** [comment]
Windows users don't need to download manually, they can use the provided instructions with Git bash.

From the README:

> Windows users are encouraged to use git bash to install the inlets binary.

I went to lengths to make sure it worked for Windows users.

Just use a git bash window and:

```sh
curl -sLS https://get.inlets.dev | sh
```

For the time being I'm not interested in maintaining a scoop repository, but am happy for you to have your own if you like?

**Comment by gldraphael** [comment]
Oh makes sense, I totally missed that.
I've added inlets to my personal repo.

> I went to lengths to make sure it worked for Windows users.

Thank you for that!

**Comment by alexellis** [comment]
Let's gauge interest - I know that some users prefer chocolatey. I would accept a PR to say that inlets can install with git bash for Windows users.

**Comment by gldraphael** [comment]
I prefer scoop for command line tools (eg. ffmpeg, 7z, etc.); Chocolatey for actually applications that need to get installed in Program Files. This is my preference though.

> I would accept a PR to say that inlets can install with git bash for Windows users.

Like you mentioned, it's already in the readme. I just missed it. Since there was brew, I guess I was expecting to see scoop or choco.
