### ISSUE TITLE
inlets server behind nginx reverse proxy

### ISSUE THREAD

**Issue by epalmans** [inlets/inlets#144]
instead of running Caddy server, I'm reverse proxying one of my subdomains to the inlets-server through Nginx (with a wildcard letsencrypt cert.).

It works pretty well actually - so as far as I'm concerened - no issue here.... 😃

But since you're encouraging use of Caddy I'm just wondering whether there might be known issues with this kind of setup using nginx?

**Comment by alexellis** [comment]
Any reverse proxy should work fine. Caddy can be achieved with about 2-5 lines of a simple DSL. If you prefer Nginx, go ahead. There's even a contrib example in the repo.

Alex
