### ISSUE TITLE
Exit Node Cloud Server for multiple Host Nodes ( home IoT devices)? Multicast?

### ISSUE THREAD

**Issue by siliconhippy** [inlets/inlets#145]
Hi Alex 😊

Just read about inlets from a hackaday.io post:

https://www.hackster.io/news/set-up-an-internet-gateway-network-for-your-home-using-a-raspberry-pi-and-https-tunnel-cda07174d06b

I am not very tech proficient, but from the gfw Chinese translation request, I had thoughts:

1. Can we have multiple Host Nodes served independently via the same Exit server in the Cloud?

There are a huge number of IoT home devices, many acting as servers, usually behind firewalls ( no control over local ISPs here.) 

People usually just  use (limiting) reverse SSH / VNC access via say, admin laptop accessing such devices via the Cloud. 

With inlets there are expanded possibilities: both manual ( individual device) control and automated FW/SW updates and management via the websockets https interface, that mimicks a restAPI.

2. How can we mod this setup for multicast video, i.e. Exit Node as multicast source and Host Nodes running igmpproxy and udpxy? 

Here Websockets run TCP I assume, but UDP should also be possible? 

Cheers 😊
Shippy.

**Comment by monelgordillo** [comment]
I'm interested in knowing the answer to this as well.

**Comment by alexellis** [comment]
Hi both, I'm not really sure what the ask is here, but you're free to experiment and feed back.

inlets OSS provides a HTTP tunnel that can have TLS added and supports websockets
inlets PRO supports any TCP traffic and has optional built-in TLS

Feel free to play around and see if you can achieve your desired results.
