### ISSUE TITLE
Control Port gets set to PORT env var

### ISSUE THREAD

**Issue by burtonr** [inlets/inlets#151]
When using environment variables for the inlets server, the control port is overridden to match the port.

## Expected Behaviour

I expect to be able to pass all parameters as environment variables

## Current Behaviour

If an env var named `PORT` is used, that value will be set for *both* the port _and_ the control-port

## Possible Solution

Take the code block starting on line 99 of `cmd/server.go` and move it before setting the control-port value (to line 89)

https://github.com/inlets/inlets/blob/master/cmd/server.go#L99

## Steps to Reproduce (for bugs)

1. Set an env var named `PORT` to a number. `export PORT=1234`
2. Set an env var named `CONTROL` to a number. `export CONTROL=4321`
3. Run the inlets server using those variables as the parameters. `inlets server -p $PORT -c $CONTROL`
4. View the output to see that the port and control port are set to `1234` (the `PORT` value)

## Context

Attempting to setup inlets server as a systemd service so that it will be available on startup. Luckily, I checked the logs to know that it is wrong. 

I had to change the variable names to get around this, but it is a surprising side-effect that is not documented

## Your Environment

* inlets version `inlets --version` 
```
Version: 2.6.3
Git Commit: c2033ecaaef9381d975a3fcadb86011056865fb9
```

* Docker/Kubernetes version `docker version` / `kubectl version`:
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04
* Link to your project or a code example to reproduce issue:
N/A

**Comment by alexellis** [comment]
Closing as inactive, happy to review a PR for this.
