### ISSUE TITLE
[Feature request] OAuth2 / SSO for HTTP connections

### ISSUE THREAD

**Issue by victorhooi** [inlets/inlets#152]
Is it possible to integrate Inlets with some kind of authentication?

For example, check for some kind of credentials/token before allowing a connection through?

(I'm thinking of something similar to Google BeyondCorp, or Cloudflare Access etc.).

**Comment by alexellis** [comment]
Thanks for the suggestion, this is not on the roadmap at present, but if you tell me more about how you'd expect this to work, I can give it consideration. You may well be able to do this by using another tool along with inlets such as OAuth2Proxy, Keycloak orAuth0. It doesn't really sound like a free OSS feature for the community, more of an enterprise support use-case, which if you have a budget for, we could of course explore separately.
