### ISSUE TITLE
Inlets server slapped newline into the token if retrieved from file

### ISSUE THREAD

**Issue by stevefan1999-personal** [inlets/inlets#154]
## Expected Behaviour
Newlines stripped

## Current Behaviour
Example:
```bash
2020/02/04 16:33:20 Server token: "b4bb8d29-e047-4861-885b-b1c754d16597\n" # umm
```
## Steps to Reproduce (for bugs)

1. `echo $(uuidgen) > /etc/default/inlets`
2. `inlets server --port=8090 -f /etc/default/inlets`
3. ???
4. Bug

## Your Environment

* uname -a, server: `Linux s 2.6.32-042stab128.2 #1 SMP Thu Mar 22 10:58:36 MSK 2018 x86_64 GNU/Linux`
* uname -a, client: `Linux serv 5.3.13-1-pve #1 SMP PVE 5.3.13-1 (Thu, 05 Dec 2019 07:18:14 +0100) x86_64 GNU/Linux`
* inlets, server/client: 2.6.3
* os, server/client: linux
* Link to your project or a code example to reproduce issue: already in the issue body lol

# Context
It's just ugly!

**Comment by alexellis** [comment]
I don't think the title of this issue is correct.

```
echo $(uuidgen) > /etc/default/inlets
```

Your file contains the new-line, it's not added by the inlets server. `echo` always prints a new-line, that's part of its deal :-)

You should just use `echo -n`

```
echo -n $(uuidgen) > token-nl
```

Alex

**Comment by stevefan1999-personal** [comment]
oh wait, so echo prints newline actually?! 
learnt something today thx ❤️

**Comment by alexellis** [comment]
Yep.. it is kind of weird.

What I've done though is to raise #155 because I think you still have a valid point. We are now going to trim the token for the client and the server, and if people want a token with a new-line at the end, I guess they are weird :-)

Alex
