### ISSUE TITLE
Support request on having sufficient write permissions in the Docker image

### ISSUE THREAD

**Issue by geertvanheusden** [inlets/inlets#157]
## Expected Behaviour
When using the following docker-compose file I expect an error to be handled and stored correctly.

```
version: '2'
services:
  inlets:
    image: inlets/inlets:2.6.3
    command: server --port=8080 --token="internal"
    ports:
     - "80:8080"
```

## Current Behaviour
The error cannot be written to a file and causes the container to stop.

```
inlets_1  | E0205 08:47:09.039358       1 upgradeaware.go:357] Error proxying data from backend to client: readfrom tcp 172.18.0.2:8080->10.0.1.127:50147: tunnel disconnect
inlets_1  | log: exiting because of error: log: cannot create log: open /tmp/inlets.ef814bc81488.unknownuser.log.ERROR.20200205-084709.1: no such file or directory
inlets_inlets_1 exited with code 2
```

## Possible Solution
Change the user that executes the inlets command.

## Steps to Reproduce (for bugs)
Copy the docker-compose file above.
For me it's unclear what caused the error to occur on the Inlets server side.

## Your Environment
OS: Debian 9.2
Inlet docker image version 2.6.3,
Docker version:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by geertvanheusden** [comment]
The answer is probably similar as: https://github.com/inlets/inlets/issues/156#issuecomment-582321337 😉 

It might be useful to mention this in the documentation...

**Comment by nimamahmoudi** [comment]
I have the same issue here. Maybe we could write the logs to another folder. The default container run command should not break with the first network error that happens, or are we doing something wrong?

**Comment by alexellis** [comment]
## On binding to low ports:

I'm a bit concerned that you're binding port 80 to the Internet, this implies you are using an insecure tunnel. It's recommended to bind to localhost on a higher port and use a tool like Nginx or Caddy to add TLS in front. Alternatively you might like to use inlets PRO.

## On logs

`/tmp/` should not be read-only or only accessible by root.

In Kubernetes we add a `tmpfs` mount for the container. Perhaps you could do the same?

docker-compose isn't documented as it's not an expected usage (I don't see what it adds over `docker run` or Kubernetes. If you can make a compelling case, maybe we can add docs with a sample.

It would seem that you can add a `tmpfs` mount relatively easily with compose: https://docs.docker.com/compose/compose-file/#tmpfs

**Comment by alexellis** [comment]
Try something like this:

```yaml
version: '3.4'
services:
  inlets-exit:
    image: inlets/inlets:2.6.3
    command: server --port=8080 --token="${TOKEN:-test1234}"
    ports:
     - "80:8080"
    tmpfs: /tmp
```
