### ISSUE TITLE
Unable to use inlets without a password

### ISSUE THREAD

**Issue by geertvanheusden** [inlets/inlets#158]
## Expected Behaviour
When no tokens are provided for both the server and the client, I can still setup a connection.

## Current Behaviour
A connection is not established

Logs on the server side:

```
inlets_1  | 2020/02/05 09:49:04 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
inlets_1  | 2020/02/05 09:49:04 Starting server - version 2.6.3
inlets_1  | 2020/02/05 09:49:04 Control Plane Listening on :8080
inlets_1  | 2020/02/05 09:49:04 Data Plane Listening on :8080
inlets_1  | 2020/02/05 09:49:08 http: multiple response.WriteHeader calls
```

Logs on the client side:

```
2020/02/05 10:49:30 Welcome to inlets.dev! Find out more at https://github.com/inlets/inlets
2020/02/05 10:49:30 Starting client - version 2.6.4
2020/02/05 10:49:30 Upstream: xxxxxxxx => http://127.0.0.1:8001
INFO[0000] Connecting to proxy                           url="ws://yyyyyyyy/tunnel"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[0000] Failed to connect to proxy                    error="websocket: bad handshake"
```

## Steps to Reproduce (for bugs)
Setup the server using the following docker-compose file:

```
version: '2'
services:
  inlets:
    image: inlets/inlets:2.6.3
    command: server --port=8080
    ports:
     - "80:8080"
```

Connect to it using the following command:

```
inlets client --remote=yyyyyyyy --upstream="xxxxxxxx=http://127.0.0.1:8001"
```

## Your Environment

* inlets version `inlets --version`
Docker image: 2.6.3
Client side: 2.6.4

* Docker/Kubernetes version `docker version` / `kubectl version`:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Server: Debian 9.3
Client: MacOS 10.14.5

**Comment by alexellis** [comment]
I am not convinced that it's a good idea to revert to unauthenticated tunnels.

What's the use-case for this?

**Comment by geertvanheusden** [comment]
In our case we use inlets to expose our developers machines to the test engineers. Both are remote and connect via VPN to our data center. We run the inlets server in our data center and we provide some internal dns names like dev1.xxx, dev2.xxx, dev3.xxx,... so a developer is free to choose one of those addresses to expose something to a test engineer (in most cases this is temporarily).

Non of this is exposed to the outside world so using a secure token has no added value for us.

**Comment by alexellis** [comment]
I have concerns about reintroducing the ability _not to set a token_. Why don't you use just a hard-coded value?

And if you're interested in working across multiple protocols and standards, check out inlets PRO, it's particularly well suited for this and support is available. https://docs.inlets.dev/

**Comment by geertvanheusden** [comment]
Using a hard-coded value is fine by me!

**Comment by alexellis** [comment]
I do think this is a little insecure. So use --token and an agreed upon value, that's shared with everyone.

If you're interested in talking about a professional solution where each engineer has their own token and you still run a single server email alex@openfaas.com
