### ISSUE TITLE
[Feature request] Add mips support

### ISSUE THREAD

**Issue by aaronchn** [inlets/inlets#160]
Many common small (home) routers use MIPS architecture CPUs, especially the MIPS xxxKc series.

As the project becomes more successful, this use case will increase.
Please consider adding support for mips architecture during release.

Thanks for this project!

**Comment by alexellis** [comment]
Hi @aaronchn I haven't had any requests for MIPS for any of my OSS work, but armhf and ARM64 are common, and there are ports for FreeBSD.

Would you be interested in trying to port inlets to MIPS for your own use and confirm back if it works?

Alex

**Comment by aaronchn** [comment]
Although I know almost nothing about golang, I will give it a try. If there are confident results, I will report them here.

**Comment by aaronchn** [comment]
I tried to build for mips arch and it seems to work.
I have listed my build process here for those who need it.

@alexellis Thanks.

My target devic:
```
root@OpenWrt:~# cat /proc/cpuinfo
system type             : Atheros AR9344 rev 2
machine                 : NETGEAR WNDR3700v4
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 278.93
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
...
```
Build environment：
```
~# uname -a
Linux amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
~# go version
go version go1.11.13 linux/amd64
~# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/golang/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072234861=/tmp/go-build -gno-record-gcc-switches"
```
Build process：
```
# cd $GOPATH
# mkdir -p $GOPATH/src/github.com/inlets
# cd $GOPATH/src/github.com/inlets
# git clone https://github.com/inlets/inlets.git
# ls
# cd inlets
# env GOOS=linux GOARCH=mips GOMIPS=softfloat CGO_ENABLED=0 \
go build -v -a -ldflags="-s -w" \
-gcflags=-trimpath=$GOPATH/src/github.com/inlets \
-asmflags=-trimpath=$GOPATH/src/github.com/inlets \
-o ./inlets_mips
```
Launch in OpenWrt：
```
root@OpenWrt:~# ./inlets_mips version
 _       _      _            _
(_)_ __ | | ___| |_ ___   __| | _____   __
| | '_ \| |/ _ \ __/ __| / _` |/ _ \ \ / /
| | | | | |  __/ |_\__ \| (_| |  __/\ V /
|_|_| |_|_|\___|\__|___(_)__,_|\___| \_/

Version: dev
Git Commit:
root@OpenWrt:~# ./inlets_mips
 _       _      _            _
(_)_ __ | | ___| |_ ___   __| | _____   __
| | '_ \| |/ _ \ __/ __| / _` |/ _ \ \ / /
| | | | | |  __/ |_\__ \| (_| |  __/\ V /
|_|_| |_|_|\___|\__|___(_)__,_|\___| \_/


Inlets combines a reverse proxy and websocket tunnels to expose your internal
and development endpoints to the public Internet via an exit-node.

An exit-node may be a 5-10 USD VPS or any other computer with an IPv4 IP address.
You can also use inlets to bridge connect between private networks.

It is strongly recommended to put a reverse proxy with TLS/SSL enabled such as
Nginx or Caddy in front of your inlets server to enable an encrypted tunnel.

See: https://github.com/inlets/inlets for more information.

Usage:
  inlets [flags]
  inlets [command]

Available Commands:
  client      Start the tunnel client.
  help        Help about any command
  server      Start the tunnel server.
  version     Display the clients version information.

Flags:
  -h, --help   help for inlets

Use "inlets [command] --help" for more information about a command.
```

**Comment by alexellis** [comment]
Thank you for the feedback. This looks positive :+1: 

If you're able to use it as expected, then could you send a quick PR and create a file in the contrib folder named `mips.md`? Please use the git command-line and run [`git commit --signoff`](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for)

This feels like a natural first step, and then I'll close the issue and continue to monitor interest. If it's strong enough, and I can get access to MIPS hardware personally then I may consider having an additional binary available.

**Comment by alexellis** [comment]
/set title: [Feature request] Add mips support

**Comment by aaronchn** [comment]
@alexellis 

My device brand is Netgear and model is 3700 v4 with 128MB RAM. See [here](https://openwrt.org/toh/netgear/wndr3700#tab__hardware_highlights) for detail. This one I bought is a cheaper second-hand one, like [here](https://www.amazon.com/gp/offer-listing/B002HWRJY4/ref=dp_olp_all_mbc?ie=UTF8&condition=all).
I'm not sure if this model is still in production, but it seems to be on [sale](https://www.amazon.com/Netgear-N600-Wireless-Router-WNDR3700/dp/B002HWRJY4/ref=sr_1_1?crid=3ELE49J9E03H3&keywords=wndr3700&qid=1581155413&sprefix=wndr+%2Caps%2C513&sr=8-1). Another [link](https://openwrt.org/toh/views/toh_available_864) that might be useful.

About quick PR, I think after a period of experience with inlets, I will try to do that.

**Comment by alexellis** [comment]
Closing this request for the time being. Let's gauge interest on the platform.
