### ISSUE TITLE
Support question on split data-plane

### ISSUE THREAD

**Issue by devbranchltd** [inlets/inlets#161]
My apologies in advance if this is the wrong place to ask a use-case question.

My use-case is as follows:
I'd like to serve an application running on 127.0.0.1:443 on a Raspberry Pi 4 (Raspbian buster) and be able to connect to it through localhost (eg. 127.0.0.1:9090) on a VM running in GCP.

I would like to be able to have an application running on the VM in GCP to connect through it's localhost to my Raspberry Pi python application running inside a shop (behind a dynamic IP).

I'd like to ask if this use-case achievable using Inlets-dev. I'd also like to check if I should write a script on the Raspberry Pi to restart the inlets client in case the public-facing IP address of the router changes for any reason, or whether this will not affect inlets client/inlets server.

**Comment by alexellis** [comment]
Hi @devbranchltd we take technical support via the Slack community, however your use-case sounds like a "split-plane" configuration.

The inlets client connects to public control-plane (control port 8080) and the data-plane is served on a local port which is not accessible by the Internet, but only services running on that host.

Here's a diagram [from inlets-pro](https://github.com/inlets/inlets-pro), does it sound like what you want?

![](https://github.com/inlets/inlets-pro/raw/master/docs/images/inlets-pro-split-plane.png)

If so, I would suggest you do the following:

Allocate a control-port i.e. 8080 to the public firewall and run inlets server with this port configured.

Tell your client to connect to that port

Set the data port (--port) to another port i.e. 8000 or 9090, and then ban this port from the security group / firewall on the GCP instance.

You now have a client that can connect from anywhere for the control-plane, but its dataplane is not accessible outside of the VM.

Alex

**Comment by devbranchltd** [comment]
@alexellis thank you for taking the time to explain that to me, I really appreciate it.

The example sounds very similar to my use-case. We have a python application acting as a hardware proxy for connecting printers and other hardware physically connected to the Pi to a python application running in the GCP instance.

The hardware proxy is running a ramdisk partition on the Pi, for /var, /etc, /tmp, etc. with everything else locked down as read-only in order to eliminate writes to the SD Card to extend it's lifetime. For this reason we will setup the inlets client to connect to our GCP instance automatically on boot.

We are not making use of Kubernetes in this case, however in my understanding of your explanation of this use-case, this should not necessarily be needed in order to achieve what I need to do.

Regarding your explanation above, we're you referring to an example setup using inlets-dev, inlets-pro, or both? If it's inlets-pro only functionality, where would I be able to purchase a license?

**Comment by alexellis** [comment]
Yes the image shows K8s, but inlets/-pro can run as a binary, Docker image, or K8s Pod. I shared the image to try to show that the control-plane can be split.

inlets and inlets-pro have slightly different pros/cons and use-cases, you should be able to get the context from the comparison in the [README](https://github.com/inlets/inlets-pro), you can also get a free trial by signing up there to test it out.

Given that this is a business use-case, would you be open to continuing the discussion over on email quoting this last message again alex@openfaas.com?
