### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by Hades32** [inlets/inlets#162]
I must admit, I didn't try this out, but when reading the code, just to learn how all this works, I stumbled upon this:

https://github.com/inlets/inlets/blob/master/pkg/client/client.go#L29

I think this is where a check to the previously given upstream(s) should happen. Otherwise a hostile server (how improbably this may be) be able to access anything on the local machine and local network.

**Comment by alexellis** [comment]
Please follow the outline for reporting suspected security issues, this does not include blaring out ideas in public.

**Comment by alexellis** [comment]
https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md

**Comment by Hades32** [comment]
Very funny, you just added this section

Alex Ellis <notifications@github.com> schrieb am Fr., 7. Feb. 2020, 20:09:

**Comment by alexellis** [comment]
Indeed, it's called responsible disclosure, which does not require someone to write this down explicitly. 

https://en.m.wikipedia.org/wiki/Responsible_disclosure

I'm not sure that what you've described is possible without someone logging into the server with ssh to deploy a malicious version of the code. At which point things are already very dire. 

I do think the upstream filtering is an interesting suggestion, we just didn't see it as a priority when implementing the remotedialer.

**Comment by alexellis** [comment]
I've opened an issue to track this. Thank you for letting us know, but please, in future - with whatever project you're looking at, consider what I linked you to on Wikipedia.
