### ISSUE TITLE
Issues when upstream server responds with brotli encoding

### ISSUE THREAD

**Issue by lwakefield** [inlets/inlets#163]
The specific error I was getting was:

```
Feb 07 20:21:13 inlets-edge-node inlets[14123]: E0207 20:21:13.958177   14123 transport.go:239] Proxy encountered encoding br for text/html; can't understand this so not fixing links.
Feb 07 20:21:13 inlets-edge-node inlets[14123]: 2020/02/07 20:21:13 httputil: ReverseProxy read error during body copy: http: read on closed response body
```

## Expected Behaviour

The `inlets` server should fallback to setting the upstream `Accept-Encoding: gzip, deflate` header.

## Current Behaviour

If the upstream server supports brotli encoding and a request is made with `Accept-Encoding: br` , then `inlets` server fail when decoding the response.

## Possible Solution

If this is out of scope of `inlets`, then perhaps it could be added to some of the examples/documentation around setting up a reverse-proxy.

```
root@inlets-edge-node:~# inlets version
 _       _      _            _
(_)_ __ | | ___| |_ ___   __| | _____   __
| | '_ \| |/ _ \ __/ __| / _` |/ _ \ \ / /
| | | | | |  __/ |_\__ \| (_| |  __/\ V /
|_|_| |_|_|\___|\__|___(_)__,_|\___| \_/

Version: 2.6.4
Git Commit: 969ffae856b36c8b92e22afd11c71d8ef9d8c173
```

Running on an Ubuntu 18.04 Server.

**Comment by alexellis** [comment]
Hi, thanks for using inlets.

What is `brotli` ? Can you provide a link?

In the meantime, while we wait for some additional context from you and reproduction instructions (you didn't give them for some reason?) You may prefer to use inlets-pro which does not get involved with the application layer, and proxies at L4 (TCP).

You can try it for free https://github.com/inlets/inlets-pro

Alex

**Comment by lwakefield** [comment]
Apologies, I made some assumptions that I suppose I shouldn't have.

[Brotli is a newer compression algorithm](https://github.com/google/brotli) which [some browsers have begun supporting](https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/).

I'll follow this comment up with reproduction instructions / PR asap.

**Comment by alexellis** [comment]
We'll monitor the levels of interest around "Brotli" and consider it on the roadmap if there is enough traction. In the time being you can use inlets PRO which does not get into the protocol, but proxies at the TCP level. I'll close the issue and track interest here.

**Comment by tanc** [comment]
I'm also bumping into this issue where an app is responding with brotli compression and inlets is failing with a read error.

**Comment by tanc** [comment]
I was able to get around the issue by manipulating the request header in Caddy (v2):

```
request_header Accept-Encoding gzip,deflate
reverse_proxy 127.0.0.1:4850
```

This overwrite the `Accept-Encoding` header to remove `br`
