### ISSUE TITLE
[Feature request] Healthcheck endpoint

### ISSUE THREAD

**Issue by rberrelleza** [inlets/inlets#167]
It would be useful to have a healthcheck endpoint in the server. 

## Context
This is particularly useful when running inlets server in a dynamic environment like Kubernetes.  It can tell us when inlets is ready to take tunnels, and /or if something is wrong.

**Comment by alexellis** [comment]
Can you tell me more about the problem you're trying to solve? What have you tried already?

**Comment by alexellis** [comment]
Also, would you expect this port to be publicly available? How would you prevent abuse? What specifically would it show?

**Comment by alexellis** [comment]
Closing as inactive, not enough information/context
