### ISSUE TITLE
[Change request] For logrus format to include timestamp

### ISSUE THREAD

**Issue by monelgordillo** [inlets/inlets#173]
Howdy,

It would be nice to have timstamps included in these messages:

INFO[0455] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF 
INFO[0020] Handling backend connection request [438c4528b7f649ebb21248a2a2cc2219]

**Comment by alexellis** [comment]
Hi @monelgordillo 

Thanks for your interest in the project.

I appreciate you are new, so may have not realised we have issue templates for a reason, but please can you fill it out as best you can anyway?

https://raw.githubusercontent.com/inlets/inlets/master/.github/ISSUE_TEMPLATE.md

Are you willing to work on a PR providing we decide to take it?

Thanks,

Alex

**Comment by alexellis** [comment]
/set title: [Change request] For logrus format to include timestamp

**Comment by alexellis** [comment]
@monelgordillo It's been a month since I commented on your issue, would you like to follow-up, or close the issue?
