### ISSUE TITLE
[Change request] Support TLS on Exit node

### ISSUE THREAD

**Issue by madhukar32** [inlets/inlets#174]
Currently, the initial tunnel is formed from client to the server on plain HTTP. It will be great to have HTTPS connection back to the server to form the tunnel. Also we should enable TLS for data server as well. Will be happy to push a PR

**Comment by Omeryl** [comment]
If I understand what you’re asking for, inlets-pro let’s you tunnel TCP so that the other end handles all of the HTTPS termination.

**Comment by madhukar32** [comment]
what I'm requesting for is, if the inital tunnel request which goes from client to server with the token is also HTTPS

**Comment by Omeryl** [comment]
Then yeah, as far as I can tell inlets-pro is what you're looking for.

**Comment by alexellis** [comment]
/set title: Support request: how to enable TLS

**Comment by alexellis** [comment]
We have instructions for adding TLS to the tunnel with the OSS project, but it's automated and built-in for inlets-pro like @Omeryl mentions. You can get a trial for free and the price for personal use is reasonable too.
