### ISSUE TITLE
[Feature Request] Add interspect proxy

### ISSUE THREAD

**Issue by dm3ch** [inlets/inlets#179]
It would be very useful to have interspect proxy and local WebUI to view requests history, like ngrock does.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets version `inlets --version` 

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thanks for the suggestion. I would suggest you use [an intercepting proxy](https://mitmproxy.org) for the time being, and I'll consider the feature for an enhanced edition of inlets.
