### ISSUE TITLE
Add option to send auth headers

### ISSUE THREAD

**Issue by manuschillerdev** [inlets/inlets#184]
If the exit node uses basic auth we can not connect to it with the client, since there is no possibility to send additional auth headers.

## Expected Behaviour
we could introduce the possibility to add additional headers to the `inlets client` command, so we can authenticate against basic auth.

## Current Behaviour
it is not possible to send additional headers with `inlets client` and therefore not possible to authenticate with basic auth.

## Possible Solution
see above

## Steps to Reproduce (for bugs)
1. Set up an exit node that uses basic auth
2. Try to connect to it with `inlets client`

## Context

I am exposing local dev-servers (e.g. webpack at localhost:3000) to the internet via k8s. It would be cool to be able to secure the tunnel with a basic auth mechanism.

## Your Environment

* inlets version `inlets --version` 
Version: 2.7.3
Git Commit: 2934c3c247ea28996ebb50889403befced94b29a

**Comment by alexellis** [comment]
> If the exit node uses basic auth we can not connect to it with the client, since there is no possibility to send additional auth headers.

This does not sound correct? OpenFaaS is an example of an application that provides basic auth and works well with inlets.

If you need deep customisation, may I suggest that you evaluate inlets PRO, which provides a pure TCP load-balancer? There you can do whatever you like. https://docs.inlets.dev/#/pricing/?id=pricing
