### ISSUE TITLE
Multiple clients connecting to a single server

### ISSUE THREAD

**Issue by AntoBud** [inlets/inlets#191]
I am wondering if it is possible to connect multiple inlet-clients to a single inlet-server?

If so, how are the multiple clients managed on the server-side?

Thanks,

**Comment by alexellis** [comment]
Hi @AntoBud we take support requests and questions through Slack on the #inlets channel. Happy to chat with you there.

There's a few patterns we have for when you need many different clients to dial back to a single exit-server or cluster.
