### ISSUE TITLE
Update the documentation to show simple user cases.

### ISSUE THREAD

**Issue by mcuix** [inlets/inlets#199]
Update the documentation to show simple user cases. For example connecting a Raspberry Pi 4 to a VPS, listing any limitations.
The current documentation requires the user to dig deep. Split instructions between ON REMOTE VPS and ON CLIENT.

**Comment by alexellis** [comment]
Hi @mcuix sorry to hear that you found it confusing to setup inlets.

I am not sure how you missed it, but we have a very detailed documentation site with lots of examples, and helper tools like inletsctl which will automate everything for you.

https://docs.inlets.dev/

Feel free to suggest specifics which you feel are not covered.

Closing the issue as resolved.
