### ISSUE TITLE
Command line option for server ca certificate

### ISSUE THREAD

**Issue by klarose** [inlets/inlets#200]
## Expected Behaviour
I'd like to be able to run an inlets server in an environment where I do not have a publicly signed TLS certificate (e.g. when testing, self hosting, etc). A simple way to allow for this is to be able to tell the inlets client to validate the server using a provided CA certificate.

## Current Behaviour
The inlets client fails to connect to the server.

## Possible Solution
A command line flag, e.g. `--ca-cert-path`, that provides the path to a local copy of the pem encoded CA Certificate.

E.g. `inlets client --remote wss://my-inlets.example.com --upstream localhost:8000 --ca-cert-path ./ca.crt`

## Context

I was trying to test out inlets in an environment running TLS, but where I do not have access to production certificates. I imagine
that I'm not the only person who wants to do this, given that many web-based tools offer similar options.

Given that I was just testing, I implemented a solution to this locally for myself. I figured I could upstream it if there's interest by the maintainers. One thing to note: I bring in an extra dependency on github.com/hashicorp/go-rootcerts as part of my solution.

**Comment by alexellis** [comment]
Thank you for the suggestion.

I think you should have a look at inlets PRO, it has a built-in CA. This is one of the differentiators on the PRO edition.

**Comment by alexellis** [comment]
One more suggestion for your use-case is to add the CA to your trust-store where you're running the inlets client, that'd also work fine.
