### ISSUE TITLE
Single Inlet Server with Multiple Inlets Client ->> Duplicate Requests

### ISSUE THREAD

**Issue by anirudhbagri** [inlets/inlets#206]
Hi there,

I have configured an inlets server on public IP and have 2 machines (to balance load) which are running my python project.
I have configured inlets client (exact same configuration) on both the machines and now the inlets server is sending messages to both the clients and duplicate requests are processed. 

Is this an expected behaviour or I have missed some configuration? 
Is there any configuration which I can change which allows me to forward the request to JUST one client?

Thank You

## Expected Behaviour
Only one of the client should get the message and process it.

## Current Behaviour
Both the clients are getting requests and processing them.

## Possible Solution
From a list of available clients forward request in a round-robbin fashion.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets version `inlets --version` -> latest

* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS): linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Closing this issue as you haven't bothered to fill out the template. We will reconsider if you take the effort to do what's asked of you in the template.

**Comment by anirudhbagri** [comment]
I have updated the issue with suggested template.

**Comment by alexellis** [comment]
You have missed some sections. You'll need to populate everything.

**Comment by anirudhbagri** [comment]
I have updated the issue.

**Comment by alexellis** [comment]
We need full instructions in "Steps to Reproduce (for bugs)" along with:
* the Python commands you ran (Are you using SimpleHTTPServer or something elsE)
* The curl commands you ran (exactly)
* What DNS entries you set up

**Comment by jsiebens** [comment]
Hi @anirudhbagri 

I have just tried to reproduce this based on what we know by your description.
The requests are only handled by the first client that has connected. I don't see any duplicated requests.

If you could give us some more information about your setup, we can give it another try to get it reproduced
