### ISSUE TITLE
Question: performance of inlets server

### ISSUE THREAD

**Issue by rohrit** [inlets/inlets#209]
Are there any performance data available on the number of inlets clients that can connect to an inlets server and number of requests than can be handled by the inlets server from the serving side?

**Comment by alexellis** [comment]
Some more context is required, however if you're looking for raw performance inlets PRO will suit you better. We would suggest you evaluate whether either solution is for you but testing your real world application.

**Comment by alexellis** [comment]
/set title: Question how many clients can connect?
