### ISSUE TITLE
Quickstart tutorial doesn't use the control port specified for the server in the inlets client --url argument

### ISSUE THREAD

**Issue by vincentdyleung** [inlets/inlets#217]
Quickstart tutorial uses port 8001 as the inlets server control port, however inlets client doesn't specify the port in the --url argument, therefore the default port 80 is used, causing problems in the inlets client.

## Expected Behaviour

Quickstart tutorial should use below as the inlets client command:
`inlets client  --url ws://$EXIT_SERVER_IP:8001  --upstream=$UPSTREAM  --token=$TOKEN`

## Current Behaviour

Currently no port is specified in the inlets client command in Quickstart tutorial.

## Possible Solution

Add the port to the inlets client command in the Quickstart tutorial.

## Steps to Reproduce (for bugs)

N/A

## Context

I couldn't start inlets client following the steps in Quickstart tutorial.

## Your Environment

* inlets version `inlets --version` 
  * 3.0.1

* Docker/Kubernetes version `docker version` / `kubectl version`:
  * N/A

* Operating System and version (e.g. Linux, Windows, MacOS):
  * Ubuntu 20.04

* Link to your project or a code example to reproduce issue:
  * N/A

**Comment by alexellis** [comment]
Thanks for the note. I've updated this now, but imagine most people are using inlets PRO now for its built-in HTTPS and TCP support.

[This weekend there's 30 USD off a 12 mo license](https://twitter.com/alexellisuk/status/1368130276166168576?s=20)

[Get a secure HTTPS tunnel with Let's Encrypt](https://inlets.dev/blog/2021/02/11/secure-letsencrypt-tunnel.html)
