### ISSUE TITLE
Typo/duplicate "to create" in README.md

### ISSUE THREAD

**Issue by rollwagen** [inlets/inlets#220]
## Expected Behaviour
Readme.md/About inlets "inlets uses a websocket to create a tunnel between a client and a server."

## Current Behaviour
Readme.md/About inlets "inlets uses a websocket to create to create a tunnel between a client and a server."

## Possible Solution
Remove duplicate

## Steps to Reproduce (for bugs)
n/a

## Context
n/a

## Are you a GitHub Sponsor for inlets?

* No

## Your Environment
n/a

**Comment by alexellis** [comment]
Thanks for the feedback.

If you're interested we have a promo on for inlets PRO this weekend "pay whatever you want" - https://gumroad.com/l/inlets-pro-personal-6mo
