### ISSUE TITLE
using inlets behind an outbound proxy

### ISSUE THREAD

**Issue by barroudjo** [inlets/inlets#222]
It seems to me the current version doesn't support outbound proxies (I didn't see any option to configure the inlets client to use one, and no mention of `http_proxy` in the source code).
ngrok does by the way: https://ngrok.com/docs#outbound-proxy.

So I assume this use case is not covered yet ? Or maybe there is a hidden option ?

**Comment by alexellis** [comment]
Hi @barroudjo we have an issue template that we encourage users to fill out before we can offer support or help.

Could you do that please?

HTTP proxies are supported in inlets PRO, you can try it out for free or buy a personal license. Personal licenses can be used at work. https://inlets.dev/

Alex

**Comment by barroudjo** [comment]
The question is so simple I thought we could bypass the template... And you understood it since you gave the answer for inlets PRO. So why not answer it for inlets NOT pro ?

**Comment by barroudjo** [comment]
OK so for anyone looking for the answer: inlets (NOT pro) does NOT support outbound proxies, at least through the `http_proxy` environment variable.
I would love to fix that, but can't since I don't know Go...
