### ISSUE TITLE
Feature request: Publish a binary for Windows

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets#23]
## Expected Behaviour

Publish a binary for Windows.

## Current Behaviour

Untested and no binary available

## Possible Solution

Update the Makefile in the `dist` section

**Comment by atefBB** [comment]
Any news about this issue?

**Comment by alexellis** [comment]
The news is that help is wanted, this needs a community contribution to edit the Makefile.

**Comment by alexellis** [comment]
@rleungx you did a good job with the last PR with versioning, would you like to take this?

**Comment by atefBB** [comment]
Thanks, I have no idea how to solve it.

**Comment by rleungx** [comment]
@alexellis Sure.

**Comment by Hokutosei** [comment]
any update on this? 
currently 
`cannot execute binary file: Exec format error`

thank you!

**Comment by alexellis** [comment]
Hi @Hokutosei you can try building from source with `go build`.

I'm still waiting for some changes on the PR from @rleungx 👋 

Alex

**Comment by alexellis** [comment]
This has been released
