### ISSUE TITLE
Feature: Logo needed for inlets

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets#46]
It would be great if someone wanted to design and donate a logo to the project.

inlets is an English word which speaks of multiple channels of water coming in from the sea. 

More here:

https://en.wikipedia.org/wiki/Inlet

Title:

> Expose your local endpoints to the Internet

Desc:

> inlets combines a reverse proxy and websocket tunnels to expose your internal and development endpoints to the public Internet via an exit-node. An exit-node may be a 5-10 USD VPS or any other computer with an IPv4 IP address.

> Why do we need this project? Similar tools such as ngrok or Argo Tunnel from Cloudflare are closed-source, have limits built-in, can work out expensive, and have limited support for arm/arm64. Ngrok is also often banned by corporate firewall policies meaning it can be unusable. Other open-source tunnel tools are designed to only set up a single static tunnel. inlets aims to dynamically bind and discover your local services to DNS entries with automated TLS certificates to a public IP address over a websocket tunnel.

**Comment by alexellis** [comment]
What I'm looking for:

- a monochrome logo without text
- a logo of only text
- a combined version with the logo and text

Will use it for creating stickers, coasters and t-shirts for end-users and fans.

**Comment by angelbarrera92** [comment]
Hi @alexellis 

What about this one?

![imagen](https://user-images.githubusercontent.com/14357604/62647278-77351300-b950-11e9-84e3-c3ae26558a7a.png)

[inlets-logo.zip](https://github.com/alexellis/inlets/files/3478373/inlets-logo.zip)

**Comment by alexellis** [comment]
It reminds me of when you need tourist information on holiday. This was generated with a logo generation website. I'd be open to see what else can be generated?

**Comment by iboonox** [comment]
What about this ?

![inlets1](https://user-images.githubusercontent.com/1584813/66719351-c08d5d00-edee-11e9-8212-f4c67ebff2ba.jpg)
![intens1-2](https://user-images.githubusercontent.com/1584813/66719352-c08d5d00-edee-11e9-9e18-183152e0f595.jpg)

**Comment by iboonox** [comment]
After some iterations with @alexellis

![inlets2](https://user-images.githubusercontent.com/1584813/66719368-e9155700-edee-11e9-811c-07e6fd6c1230.jpg)
![inlets3](https://user-images.githubusercontent.com/1584813/66719369-e9155700-edee-11e9-9769-59608fac09ca.jpg)
![inlets4](https://user-images.githubusercontent.com/1584813/66719370-e9155700-edee-11e9-9254-da6a4173ee99.jpg)

 

![Logo](https://user-images.githubusercontent.com/1584813/66719372-f2062880-edee-11e9-8ce1-6c651813fc14.jpg)

**Comment by alexellis** [comment]
I'm really excited about this logo. Thank you so much 🎉

**Comment by alexellis** [comment]
Here's the first t-shirt, next up - stickers.

https://twitter.com/alexellisuk/status/1188077598221488128?s=20

The media is in the https://github.com/inlets/media repo

**Comment by zenzx** [comment]
This is very cool!!!

**Comment by alexellis** [comment]
Thank you
