### ISSUE TITLE
Feature request: HTTP healthcheck endpoint

### ISSUE THREAD

**Issue by rycus86** [inlets/inlets#74]
Some (most) platforms require services running on them to tell if they're healthy or not. Most of these systems can periodically ping an HTTP endpoint on the services to detect if they're healthy, indicated by HTTP 200 OK, or unhealthy otherwise. I'd propose having some configuration for the server part of inlets that would enable such an endpoint.

## Possible Solution

By accepting a port number and optionally a path, we could configure an endpoint to return HTTP 200 OK. We could potentially add some extra information on the responses that is a pattern in some other systems, but it's not necessary.

Let me know what do you think! I'm happy to raise a PR for this.

Thank you!

**Comment by alexellis** [comment]
Would you be OK if this was on an "internal"-style name? i.e. `/_/health`?

You'd have to be aware that whatever endpoint we want to use, it will potentially clash with the forwarded application.

Which end of the tunnel would you like to see this?

Alex

**Comment by rycus86** [comment]
Yeah, I was originally thinking passing in the endpoint path with the parameter, because in each use case the safe, non-clashing path could be different.

I'd need this on the server side, so the server deployment can tell load-balancers and such that it's ready. Since then, we've actually done this with an Nginx in front of inlets, so the healthcheck returns 200, `/tunnel` is passed in to inlets to set up the websocket connection, and everything else is `proxy_pass`ed to the inlets server.

So what I want to say is that we have a sensible workaround if you have concerns about adding more features or potentially masking paths.

Thanks!

**Comment by alexellis** [comment]
Can you share your config file here and redact the confidential bits?

**Comment by rycus86** [comment]
Yep, will do when I'm at work. :+1:

**Comment by alexellis** [comment]
Can you share what you're using inlets for? Perhaps, if you can and it's interesting, we could add it to the README file? https://github.com/alexellis/inlets#what-are-people-saying-about-inlets

**Comment by rycus86** [comment]
Sure, I'll check what we can share.

**Comment by rycus86** [comment]
> Can you share your config file here and redact the confidential bits?

The relevant Nginx config looks something like this:
```
upstream backend {
    server inlets:8000 max_fails=0;
    keepalive 10;
}

server {

    # static healthcheck to return HTTP 200 OK
    location /healthcheck {
         return 200 'OK';
         add_header  Content-Type text/plain;
    }

    # handle inlets connection setup requests
    location /tunnel {
        # required headers for websocket setup
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://backend;
    }

    # forward any other traffic to the backend
    location / {
        proxy_http_version 1.1;
        
        # forward all request headers
        proxy_pass_request_headers on;

        proxy_pass http://backend;
    }

}
```

Will try to prepare something more structured to share and link to the README. :+1:

**Comment by alexellis** [comment]
Thanks.. I'll look forward to your PR with a link to your repo or blog post.

**Comment by alexellis** [comment]
This may be related to: https://github.com/alexellis/inlets/pull/73

**Comment by alexellis** [comment]
If you still want to work on this @rycus86 then please send a PR and I'll reopen the issue.

The /tunnel endpoint can now be served on a new control port, so we don't strictly have to worry about clashing URLs, it could be /healthz.
