### ISSUE TITLE
Feature: Add figlet ASCII logo

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets#83]
## Description

We could make the `version` / help message look better than this:

![](https://pbs.twimg.com/media/ECUKAhaW4AALnjg?format=jpg&name=medium)

By including a figlet ASCII logo as per [faas-cli](https://github.com/openfaas/faas-cli/blob/master/commands/version.go#L159)

To generate a logo you can use the `figlet` package available on most Linux package managers and in the OpenFaaS function store. 

Get a logo like this:

```sh
docker run -ti functions/figlet figlet inlets.dev
```

^ that will generate a logo.

The link I included above was to the code where it's implemented in the faas-cli -> https://github.com/openfaas/faas-cli/blob/master/commands/version.go#L159

This approach can be copied.

**Comment by linuxjuggler** [comment]
Hey @alexellis , Something like this should be fine?

![Screen Shot 2019-08-19 at 12 29 47 PM](https://user-images.githubusercontent.com/27624/63254829-17f2cf00-c27d-11e9-9e94-5e8d8a698bea.png)

**Comment by titanic-one** [comment]
hello We are a student in computer science and we develop for our school a site of downloading of the duty and subject in all the matter but we are jam at a level or? we want every student who connects to the site can only download two homework per day. if someone has a tutorial on it or how can it be done. thank you in advance

**Comment by alexellis** [comment]
This has been done
