### ISSUE TITLE
Add AWS provisioning scripts for Lightsail and EC2

### ISSUE THREAD

**Issue by mbacchi** [inlets/inlets#88]
This is not a bug, rather a feature request.

I've prepared two scripts to provision AWS Lightsail and EC2 instances as Inlets exit nodes. I'll open a PR momentarily for this.

**Comment by alexellis** [comment]
Hi @mbacchi 

All issues should first be approved before being worked.

This is explained in the [contribution guide](https://github.com/alexellis/inlets/blob/master/CONTRIBUTING.md#guidelines)

Part of submitting a PR is acknowledging that you [have read the guide](https://github.com/alexellis/inlets/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and that you agree to it.

I'm not sure where the disconnect was, but I've commented on the PR and I hope we can use your work in some way.

Alex

**Comment by alexellis** [comment]
It'd be great to have your blog post listed in README.md, thanks for the PR, happy to link to your repo when it's ready too.
