### ISSUE TITLE
Support question for Caddy

### ISSUE THREAD

**Issue by yunfan** [inlets/inlets#94]
> inlet behind caddy cant support any domain

i am not familliar with caddy, but i dont want to use it without any encryption , so i tried the ssl solution from README, it works except the user customer domain dont support . i dont know if its caddy's problem or inlet's ?

**Comment by alexellis** [comment]
If you follow the tutorial instructions step-by-step, it works well.

You run `inlets server` and `caddy` on the same server with an IPv4 address.

It uses a HTTP01 challenge, so I can't think of any reason why it would not work for you.

Can you give me more info?

* `inlets version`
* Host for the server VM
* what exact steps I can take to reproduce the problem you're facing

**Comment by alexellis** [comment]
Try:

`/etc/systemd/system/inlets.service`

`ExecStart=/usr/local/bin/inlets server --port=80 --token="${AUTHTOKEN}"`

to:

`ExecStart=/usr/local/bin/inlets server --port=8080 --token="${AUTHTOKEN}"`

Then:

`sudo systemctl daemon-reload && sudo systemctl restart inlets`

**Comment by alexellis** [comment]
I have this running on DigitalOcean including basic auth support. 

I'll really need *more information* from you to be able to help as this worked fine for me using the guide and above.

**Comment by yunfan** [comment]
the version is `2.4.1` at both sides
and i think you might misunderstand this. i mean i follow the README, it works.
but only works on the specific domain. while on the other examples of README,  we could set customized domain when using inlet with upstream paramaters

for eg, my exit node's domain is `inlet.example.com`, i had a dns record on that, and by using 
`inlet client -t xxx -r inlet.example.com -u http://127.0.0.1:8080` , it could works exactly

but while i use `inlet client -t xxx -r inlet.example.com -u "other.example.com=http://127.0.0.1:8080"`

and modified my /etc/hosts to add a relative record for `other.example.com`
then when i accessing it, i found a error indicating that `404 Site xx.example.com is not served on this interface`

**Comment by mcgregorjenny** [comment]
Good luck

**Comment by alexellis** [comment]
@mcgregorjenny what is "good luck" meant to mean?

@yunfan there's no issues with Caddy, I have it working just fine with LetsEncrypt? What are you not telling us? 

Maybe if you used the issue template we could try to reproduce your problem? https://raw.githubusercontent.com/inlets/inlets/master/.github/ISSUE_TEMPLATE.md

In any case, I'll close this as it looks inactive and if you need more help, just comment again
