### ISSUE TITLE
[Feature] Add provisioning script which also configures Caddy

### ISSUE THREAD

**Issue by alexellis** [inlets/inlets#95]
## Description

I'd like to see a script like the one which configures a new VM and installs inlets, but that also goes one step further and adds Caddy and a generated Caddyfile for a given domain.

This would bring us even closer to a "1-click" inlets experience, with TLS.

Current file:

https://github.com/alexellis/inlets/blob/master/hack/provision-digitalocean.sh

The proposal would be to add a flag like `--add-tls` and `--domain inlets.my-free-domain.tk`

My understanding from Matt Holt is that Caddy is now free for commercial use including use of the pre-compiled binary.

**Comment by joeblew99** [comment]
Any change that all with logic can then be done at the caddy level since it protects the inlets server (s) now ?

**Comment by alexellis** [comment]
I believe that Caddy can use your own CA yep.. do you want to prototype it and report back?

Just so you're aware, this issue is for LetsEncrypt.

**Comment by marcosvrs** [comment]
@alexellis are you fine if I create a PR first for the gcloud hack? I already have a working solution.

**Comment by alexellis** [comment]
Feel free to put something up in a repo, no need to ask for permission to try something out.

**Comment by alexellis** [comment]
Closing as inactive
