### ISSUE TITLE
Server logs "suppressing panic ... context canceled" for Server-Sent Events

### ISSUE THREAD

**Issue by matthewmueller** [inlets/inlets#96]
Okay this is pretty minor, but as soon as I close the webpage tab, I'm noticing a suppressed panic in the log. Nothing is breaking though which is the most important ☺️

## Expected Behaviour

Non-panicky shut downs

## Current Behaviour

```
suppressing panic for copyResponse error in test; copy error: context canceled
```

## Possible Solution

It's related to `http://localhost:8000/__webpack_hmr`. Webpack's dev server opens a long-running Server-Sent event stream, so when I close the page abruptly, the server's connection gets abruptly shutdown.

## Steps to Reproduce (for bugs)

I think your React App demo would properly demonstrate this since as far as I know, they also use Webpack's hot module reload.

## Context

Like I said, super minor in an otherwise flawlessly functioning piece of software 💯 

## Your Environment

* inlets version `inlets --version` 

Version: 2.4.1
Git Commit: 5d9330c259b84d6957c6a5b291e5622263ec876d

**Minor sidenote:** `inlets --version` is out of date. It should be `inlets version`

* Operating System and version (e.g. Linux, Windows, MacOS):

OSX

**Comment by alexellis** [comment]
@ibuildthecloud have you got any thoughts on this re: remotedialer?

**Comment by rusenask** [comment]
this is normal behavior from go standard lib, can't do much about it :)
